# Labeler configuration
labels:
  - name: documentation
    pattern: ['*.md', 'docs/**']
  - name: bug
    pattern: ['**/test/**', '**/tests/**']
  - name: dependencies
    pattern: ['package.json', 'bun.lock']
  - name: ci/cd
    pattern: ['.github/**']
  - name: packages
    pattern: ['packages/**']

only: PRs
