documentation:
  - changed-files:
      - any-glob-to-any-file: ['*.md', 'docs/**']

bug:
  - changed-files:
      - any-glob-to-any-file: ['**/test/**', '**/tests/**']

dependencies:
  - changed-files:
      - any-glob-to-any-file: ['package.json', 'bun.lock']

ci/cd:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']

packages:
  - changed-files:
      - any-glob-to-any-file: ['packages/**']
