module.exports = {
	extends: ["@commitlint/config-conventional"],
	rules: {
		"type-enum": [
			2,
			"always",
			[
				"feat",
				"fix",
				"docs",
				"style",
				"refactor",
				"perf",
				"test",
				"build",
				"ci",
				"chore",
				"revert",
			],
		],
		"scope-enum": [
			2,
			"always",
			[
				"ai",
				"compute",
				"functions",
				"storage",
				"flags",
				"logging",
				"notifications",
				"repo",
				"deps",
				"ci",
				"release",
				"docs",
				"scripts",
				"misc",
			],
		],
		"type-empty": [2, "never"],
		"scope-empty": [2, "never"],
		"subject-empty": [2, "never"],
		"subject-full-stop": [2, "never", "."],
		"header-max-length": [2, "always", 100],
	},
};
