name: Bug report
description: Report an issue with the Frontal SDK
labels: [bug]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Package affected
      description: Select the package that is affected by the bug
      options:
        - "@frontal-labs/agents"
        - "@frontal-labs/ai"
        - "@frontal-labs/blob"
        - "@frontal-labs/core"
        - "@frontal-labs/functions"
        - "@frontal-labs/graph"
        - "@frontal-labs/ontology"
        - "@frontal-labs/pipelines"
        - "@frontal-labs/testing"
        - "@frontal-labs/workflows"
        - "multiple / unsure"
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide steps to reproduce the issue.
      placeholder: |
        1. Install with `bun install`
        2. Import package
        3. Call method...
  - type: input
    id: reproduction
    attributes:
      label: Reproduction URL
      description: A link to a minimal reproduction repository is very helpful.
      placeholder: https://github.com/your-username/repro
    validations:
      required: false
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `bun --version` and `uname -a`
      render: shell
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      description: Which package manager are you using?
      options:
        - bun
        - npm
        - yarn
        - pnpm
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Provide the error log here.

        ````
        <details>
        <summary>Click to expand!</summary>

        ```shell
        // paste the log text here
        ```
        </details>
        ````
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      options:
        - label: I have read the [Code of Conduct](https://github.com/frontal-labs/sdk-typescript/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/frontal-labs/sdk-typescript/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have checked that there isn't already an issue that reports the same bug
          required: true
        - label: I have provided a minimal reproducible example where possible
          required: true
