name: Feature request
description: Propose a new feature for the Frontal SDK
labels: ['enhancement']
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project!
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: Clear and concise description of the problem or use case.
      placeholder: As a developer using the Frontal SDK I want [goal / wish] so that [benefit].
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: How could this be implemented?
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: Any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      options:
        - label: I have read the [Code of Conduct](https://github.com/frontal-labs/sdk-typescript/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/frontal-labs/sdk-typescript/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have checked that there isn't already an issue requesting the same feature
          required: true
